<wsdl:definitions
     name="pruebaDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CI-Test/Test/pruebaDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CI-Test/Test/pruebaDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/pruebaDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="pruebaDB_plt" >
    <plt:role name="pruebaDB_role" >
      <plt:portType name="tns:pruebaDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/pruebaDB" schemaLocation="pruebaDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="pruebaDBSelect_inputParameters">
        <wsdl:part name="pruebaDBSelect_inputParameters" element="top:pruebaDBSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EstadosCollection_msg">
        <wsdl:part name="EstadosCollection" element="top:EstadosCollection"/>
    </wsdl:message>
    <wsdl:portType name="pruebaDB_ptt">
        <wsdl:operation name="pruebaDBSelect">
            <wsdl:input message="tns:pruebaDBSelect_inputParameters"/>
            <wsdl:output message="tns:EstadosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
