<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CI-Test/Test/pruebaDB" name="pruebaDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="pruebaDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CI-Test/Test/pruebaDB"/>
    <wsdl:binding name="pruebaDB_ptt-binding" type="pru:pruebaDB_ptt" xmlns:pru="http://xmlns.oracle.com/pcbpel/adapter/db/CI-Test/Test/pruebaDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="pruebaDBSelect">
            <soap:operation soapAction="pruebaDBSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>